# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 13:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_made',
            name='parent',
        ),
        migrations.AddField(
            model_name='child',
            name='parent_email',
            field=models.EmailField(max_length=75, null=True, verbose_name='Email родителя'),
        ),
        migrations.AddField(
            model_name='child',
            name='parent_phone',
            field=models.CharField(max_length=30, null=True, verbose_name='Телефон родителя'),
        ),
        migrations.AddField(
            model_name='child',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Логин'),
        ),
        migrations.AddField(
            model_name='payment_made',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.Child', verbose_name='ФИО ребенка'),
        ),
        migrations.AddField(
            model_name='payment_needed',
            name='address',
            field=models.CharField(choices=[('С', 'Сад'), ('Г', 'Группа')], max_length=10, null=True, verbose_name='Куда'),
        ),
        migrations.AlterField(
            model_name='child',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='ФИО ребенка'),
        ),
        migrations.AlterField(
            model_name='child',
            name='parent',
            field=models.CharField(max_length=200, null=True, verbose_name='ФИО родителя'),
        ),
        migrations.AlterField(
            model_name='payment_needed',
            name='category',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Категория'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
