# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20170710_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=75, null=True, verbose_name='Email родителя'),
        ),
        migrations.AlterField(
            model_name='child',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Телефон родителя'),
        ),
    ]
