# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20170710_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name': 'Ребенок', 'verbose_name_plural': 'Дети'},
        ),
        migrations.AlterModelOptions(
            name='payment_made',
            options={'verbose_name': 'Выполненный платеж', 'verbose_name_plural': 'Выполненные платежи'},
        ),
        migrations.AlterModelOptions(
            name='payment_needed',
            options={'verbose_name': 'Необходимый платеж', 'verbose_name_plural': 'Необходимые платежи'},
        ),
    ]
