# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20170710_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_made',
            name='payment_date',
            field=models.DateField(),
        ),
    ]
