# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_child_total_payed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='total_payed',
        ),
        migrations.AlterField(
            model_name='payment_made',
            name='contribution',
            field=models.SmallIntegerField(verbose_name='Сумма'),
        ),
    ]
