# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_auto_20170711_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_needed',
            name='reckoning',
            field=models.SmallIntegerField(verbose_name='Сумма'),
        ),
    ]
