# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_auto_20170711_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_made',
            name='contribution',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='payment_made',
            name='payment_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payment_needed',
            name='reckoning',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма'),
        ),
    ]
